pipeline {
    agent any
    
    environment {
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/react-app']],
                          userRemoteConfigs: [[url: 'git@github.com:fahrul327/a428-cicd-labs.git']]])
            }
            post {
                success {
                    script {
                        sh 'git pull'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.image('node:16-buster-slim').inside('-p 3000:3000') {
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
